### ISSUE TITLE
Separar tickets por tipo de Ventas

### ISSUE THREAD

**Issue by RamsesMartinez** [DigimundoTesca/CloudKitchen-KeffKaffe#26]
- [x] Verificar funcionamiento de botons de tipo de venta
- [x] Añadir el tipo de venta en los tickets
- [x] Separar las ventas de acuerdo al tipo de pago en el template de Analytics de Ventas

**Comment by RichDi** [comment]
Verificado funcionamiento de botones
A;;adido tipo de venta en tickets
Agregado campo "tipo de venta" a tabla de tickets en analytics

**Comment by RamsesMartinez** [comment]
Revisaré el codigo en tu rama

**Comment by RamsesMartinez** [comment]
@RichDi No logro identificar cuáles tickets están activos y cuáles no, hay que lograr que sean resaltados de alguna manera por favor :)

**Comment by RamsesMartinez** [comment]
Issue terminado
