### ISSUE TITLE
Modificar funcionamiento de borrar tickets

### ISSUE THREAD

**Issue by RamsesMartinez** [DigimundoTesca/CloudKitchen-KeffKaffe#27]
En la pantalla de Analytics de Ventas, existe un boton para eliminarlos, hay que alterar el funcionamiento para que no los elimine, sino que cambie el estado del ticket a "desactivado" modificando el siguiente modelo:

El modelo de Ticket hay que añadirle un nuevo campo llamado "is_active" el cual, tendrá como default: True, además de que al presinar el boton de "eliminar" lo que se hará realmente es que sea ignorado el ticket para los analytics y que no sea visible en la tabla de ventas.

También se necesita validar que las graficas de ventas sean rellenadas sólo con los tickets activos.

Por último, la única persona que sea capaz de ver los tickets será la que tenga el nivel de superusuario.

**Comment by RichDi** [comment]
Agreado campo is_active al modelo
Modificado funcionamiento del boton delete
Validadas graficas para mostrar solo tickets con campo is_active = True

**Comment by RamsesMartinez** [comment]
Entonces las listas  de tareas Terminadas que pasan a revisión
- [x] Agregado campo is_active al modelo
- [x] Modificado funcionamiento del boton delete
- [x] Validadas graficas para mostrar solo tickets con campo is_active = True

Tareas pendientes:
- [x] Lograr que sólo usuarios con permisos de superusuario puedan ver tanto tickets descativados como activos
- [x] Mostrar sólo los tickets activos en la tabla de tickets
- [x] Reestablecer el Helper a como estaba antes y el filtro usado para llamar a los tickets colocarlo en la vista que lo llame.

**Comment by RichDi** [comment]
Listo Tickets Activos en la tabla de tickets

**Comment by RamsesMartinez** [comment]
@RichDi las tareas pendientes por terminar son estas:

- [x]  Lograr que sólo usuarios con permisos de superusuario puedan ver tanto tickets descativados como activos
- [x]  Reestablecer el Helper a como estaba antes y el filtro usado para llamar a los tickets colocarlo en la vista que lo llame.

**Comment by RichDi** [comment]
Agregada funcion para visualizacion de todos los tickets por SuperUsuario
Restablecido Helper y movido filters a view
