### ISSUE TITLE
Etiqueta para total de tickets (SuperU)

### ISSUE THREAD

**Issue by RichDi** [DigimundoTesca/CloudKitchen-KeffKaffe#28]
- [x] Agregar una etiqueta a que muestra el total de gasto de tickets activados

- [x] Agregar una etiqueta a que muestra el total de gasto de tickets activados y desactivados

**Comment by RichDi** [comment]
Agregada etiqueta con total de tickets activados
Agregada etiqueta con total de tickets activados y desactivados

**Comment by RamsesMartinez** [comment]
Issue terminado procedo a cerrarlo
