### ISSUE TITLE
Añadir nuevo icon_font en ventas

### ISSUE THREAD

**Issue by RamsesMartinez** [DigimundoTesca/CloudKitchen-KeffKaffe#31]
Se debe agregar un nuevo ícono para poder eliminar definitivamente los tickets, el cual sólo los superusuarios pueden visualizar.
Cuando un ticket haya sido desactivado por un usuario normal, el superusuario debe visualizar el ticket resaltado y el icono que antes era un tache para desactivar, se debe cambiar por otro icono para poder reactivarlo, sólo por el superusuario.

**Comment by RichDi** [comment]
Terminado el add de Icons y sus funcionalidades para SuperUsuario
